<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ReagentPlanning;

class ReagentPlanningSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI001', 'descripcion' => 'AFIAS NT-PROBNP X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI002', 'descripcion' => 'AFIAS PSA NEO X 24 TEST', 'stock' => 30],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI003', 'descripcion' => 'AFIAS FPSA NEO X 24 TEST', 'stock' => 15],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI004', 'descripcion' => 'AFIAS AFP X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI005', 'descripcion' => 'AFIAS HBA1C NEO (HEMOGLOBINA GLICOSILADA) X 24 TEST', 'stock' => 81],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI006', 'descripcion' => 'AFIAS INSULINA X 24 TEST', 'stock' => 23],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI007', 'descripcion' => 'AFIAS TSH X 24 TEST', 'stock' => 115],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI008', 'descripcion' => 'AFIAS T3 X 24 TEST', 'stock' => 10],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI009', 'descripcion' => 'AFIAS T4 X 24 TEST', 'stock' => 15],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI010', 'descripcion' => 'AFIAS FT4 X 24 TEST', 'stock' => 20],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI011', 'descripcion' => 'AFIAS FSH X 24 TEST', 'stock' => 7],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI012', 'descripcion' => 'AFIAS PRL (PROLACTINA) X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI013', 'descripcion' => 'AFIAS TESTOSTERONA X 24 TEST', 'stock' => 5],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI014', 'descripcion' => 'AFIAS CORTISOL X 24 TEST', 'stock' => 3],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI015', 'descripcion' => 'AFIAS HELICOBACTER PYLORI SA X 24 TEST', 'stock' => 104],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI016', 'descripcion' => 'AFIAS CRP (PROTEINA C REACTIVA) X 24 TEST', 'stock' => 39],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI017', 'descripcion' => 'AFIAS PROCALCITONINA (PCT) X 24 TEST', 'stock' => 9],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI018', 'descripcion' => 'AFIAS TOXO IGG X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI019', 'descripcion' => 'AFIAS TOXO IGM X 24 TEST', 'stock' => 1],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI020', 'descripcion' => 'AFIAS RUBEOLLA IGG X 24 TEST', 'stock' => 1],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI021', 'descripcion' => 'AFIAS TOTAL IGE X 24 TEST', 'stock' => 15],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI022', 'descripcion' => 'AFIAS FERRITINA X 24 TEST', 'stock' => 5],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI023', 'descripcion' => 'AFIAS VITAMINA D NEO X 24 TEST', 'stock' => 20],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI024', 'descripcion' => 'AFIAS TSH X 24 TEST R', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI025', 'descripcion' => 'AFIAS HBA1C NEO (HEMOGLOBINA GLICOSILADA) X 24 TEST R', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI027', 'descripcion' => 'AFIAS TNI PLUS X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI028', 'descripcion' => 'AFIAS CK-MB NEO X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI029', 'descripcion' => 'AFIAS D-DIMER NEO X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI030', 'descripcion' => 'AFIAS CARDIAC TRIPLE X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI031', 'descripcion' => 'AFIAS HSCRP X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI032', 'descripcion' => 'AFIAS TROPONIN T X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI033', 'descripcion' => 'AFIAS CEA X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI034', 'descripcion' => 'AFIAS CA 19-9 X 24 TEST', 'stock' => 3],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI035', 'descripcion' => 'AFIAS CA 125 X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI036', 'descripcion' => 'AFIAS CYFRA 21-1 X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI037', 'descripcion' => 'AFIAS MICROALBUMIN X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI038', 'descripcion' => 'AFIAS CYSTATIN C X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI039', 'descripcion' => 'AFIAS TOTAL BHCG X 24 TEST', 'stock' => 3],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI040', 'descripcion' => 'AFIAS LH X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI041', 'descripcion' => 'AFIAS PROGESTERONE X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI042', 'descripcion' => 'AFIAS ESTRADIOL X 24 TEST', 'stock' => 3],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI043', 'descripcion' => 'AFIAS AMH X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI044', 'descripcion' => 'AFIAS CALPROTECTIN X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI045', 'descripcion' => 'AFIAS COVID-19 AB X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI046', 'descripcion' => 'AFIAS COVID-19 AG X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI047', 'descripcion' => 'AFIAS COVID-19/FLU AG COMBO X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI049', 'descripcion' => 'AFIAS ANTI-HBS X 24 TEST', 'stock' => 4],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI050', 'descripcion' => 'AFIAS ANTI-HCV X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI051', 'descripcion' => 'AFIAS DENGUE IGG/IGM X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI052', 'descripcion' => 'AFIAS DENGUE NS1 AG X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI053', 'descripcion' => 'AFIAS HIV 1/2 AB X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI054', 'descripcion' => 'AFIAS NORO X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI055', 'descripcion' => 'AFIAS ROTA X 24 TEST', 'stock' => 1],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI056', 'descripcion' => 'AFIAS ROTA/ADENO X 24 TEST', 'stock' => 3],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI057', 'descripcion' => 'AFIAS STREP A X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI058', 'descripcion' => 'AFIAS FLU A+B X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI059', 'descripcion' => 'AFIAS ANTI-CCP PLUS, 108 X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI060', 'descripcion' => 'AFIAS PTH X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI062', 'descripcion' => 'AFIAS COVID-19/FLU A+B/RSV AG X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI066', 'descripcion' => 'GT-AFIAS CEA X 24 TEST', 'stock' => 2],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI067', 'descripcion' => 'GT-AFIAS DENGUE IGG/IGM X 24 TEST', 'stock' => 39],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI068', 'descripcion' => 'GT-AFIAS FT4 X 24 TEST', 'stock' => 1],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LEAFI001', 'descripcion' => 'EQUIPO AFIAS-1', 'stock' => -1],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI001', 'descripcion' => 'AFIAS NT-PROBNP X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI002', 'descripcion' => 'AFIAS PSA NEO X 24 TEST', 'stock' => 30],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI003', 'descripcion' => 'AFIAS FPSA NEO X 24 TEST', 'stock' => 8],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI004', 'descripcion' => 'AFIAS AFP X 24 TEST', 'stock' => 3],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI005', 'descripcion' => 'AFIAS HBA1C NEO (HEMOGLOBINA GLYCOSILADA) X 24 TEST', 'stock' => 26],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI006', 'descripcion' => 'AFIAS INSULINA X 24 TEST', 'stock' => 7],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI007', 'descripcion' => 'AFIAS TSH X 24 TEST', 'stock' => 17],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI008', 'descripcion' => 'AFIAS T3 X 24 TEST', 'stock' => 10],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI009', 'descripcion' => 'AFIAS T4 X 24 TEST', 'stock' => 18],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI010', 'descripcion' => 'AFIAS FT4 X 24 TEST', 'stock' => 11],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI011', 'descripcion' => 'AFIAS FSH X 24 TEST', 'stock' => 7],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI012', 'descripcion' => 'AFIAS PRL (PROLACTINA) X 24 TEST', 'stock' => 6],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI013', 'descripcion' => 'AFIAS TESTOSTERONA X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI014', 'descripcion' => 'AFIAS CORTISOL X 24 TEST', 'stock' => 5],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI015', 'descripcion' => 'AFIAS HELICOBACTER PYLORI SA X 24 TEST', 'stock' => 43],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI016', 'descripcion' => 'AFIAS CRP (PROTEINA C REACTIVA) X 24 TEST', 'stock' => 25],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI017', 'descripcion' => 'AFIAS PROCALCITONINA (PCT) X 24 TEST', 'stock' => 9],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI018', 'descripcion' => 'AFIAS TOXO IGG X 24 TEST', 'stock' => 1],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI019', 'descripcion' => 'AFIAS TOXO IGM X 24 TEST', 'stock' => 1],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI020', 'descripcion' => 'AFIAS RUBEOLLA IGG X 24 TEST', 'stock' => 1],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI021', 'descripcion' => 'AFIAS TOTAL IGE X 24 TEST', 'stock' => 3],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI022', 'descripcion' => 'AFIAS FERRITINA X 24 TEST', 'stock' => 7],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI023', 'descripcion' => 'AFIAS VITAMINA D NEO X 24 TEST', 'stock' => 9],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI024', 'descripcion' => 'AFIAS TSH X 24 TEST R', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI025', 'descripcion' => 'AFIAS HBA1C NEO (HEMOGLOBINA GLYCOSILADA) X 24 TEST R', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI026', 'descripcion' => 'AFIAS TNI PLUS X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI027', 'descripcion' => 'AFIAS TNI PLUS X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI028', 'descripcion' => 'AFIAS CK-MB NEO X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI029', 'descripcion' => 'AFIAS D-DIMER NEO X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI030', 'descripcion' => 'AFIAS CARDIAC TRIPLE X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI031', 'descripcion' => 'AFIAS HSCRP X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI032', 'descripcion' => 'AFIAS TROPONIN T X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI033', 'descripcion' => 'AFIAS CEA X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI034', 'descripcion' => 'AFIAS CA 19-9 X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI035', 'descripcion' => 'AFIAS CA 125 X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI036', 'descripcion' => 'AFIAS CYFRA 21-1 X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI037', 'descripcion' => 'AFIAS MICROALBUMIN X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI038', 'descripcion' => 'AFIAS CYSTATIN C X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI039', 'descripcion' => 'AFIAS TOTAL BHCG X 24 TEST', 'stock' => 3],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI040', 'descripcion' => 'AFIAS LH X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI041', 'descripcion' => 'AFIAS PROGESTERONE X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI042', 'descripcion' => 'AFIAS ESTRADIOL X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI043', 'descripcion' => 'AFIAS AMH X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI044', 'descripcion' => 'AFIAS CALPROTECTIN X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI045', 'descripcion' => 'AFIAS COVID-19 AB X 24 TEST', 'stock' => 3],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI046', 'descripcion' => 'AFIAS COVID-19 AG X 24 TEST', 'stock' => 3],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI047', 'descripcion' => 'AFIAS COVID-19/FLU AG COMBO X 24 TEST', 'stock' => 0],
            ['asesor' => 'JORGE ESTRELLA', 'cod_item' => 'LRAFI048', 'descripcion' => 'AFIAS HBSAG X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI049', 'descripcion' => 'AFIAS ANTI-HBS X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI050', 'descripcion' => 'AFIAS ANTI-HCV X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI051', 'descripcion' => 'AFIAS DENGUE IGG/IGM X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI052', 'descripcion' => 'AFIAS DENGUE NS1 AG X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI053', 'descripcion' => 'AFIAS HIV 1/2 AB X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI054', 'descripcion' => 'AFIAS NORO X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI055', 'descripcion' => 'AFIAS ROTA X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI056', 'descripcion' => 'AFIAS ROTA/ADENO X 24 TEST', 'stock' => 3],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI057', 'descripcion' => 'AFIAS STREP A X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI058', 'descripcion' => 'AFIAS FLU A+B X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI059', 'descripcion' => 'AFIAS ANTI-CCP PLUS, 108 X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI060', 'descripcion' => 'AFIAS PTH X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI062', 'descripcion' => 'AFIAS COVID-19/FLU A+B/RSV AG X 24 TEST', 'stock' => 0],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI063', 'descripcion' => 'AFIAS IL-6 X 24 TEST', 'stock' => 1],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI066', 'descripcion' => 'GT-AFIAS CEA X 24 TEST', 'stock' => 2],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI067', 'descripcion' => 'GT-AFIAS DENGUE IGG/IGM X 24 TEST', 'stock' => 39],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI068', 'descripcion' => 'GT-AFIAS FT4 X 24 TEST', 'stock' => 1],
            ['asesor' => 'INGELAB CORP', 'cod_item' => 'LRAFI048', 'descripcion' => 'AFIAS HBSAG X 24 TEST', 'stock' => 0]
        ];

        foreach ($data as $item) {
            ReagentPlanning::create($item + [
                'cliente' => 'Hospital Metropolitano', // Default seeder client
                'rotacion_mensual' => 0.00,
                'uso_4_meses' => 0.00,
                'cantidad_importar' => 0.00,
                'total' => 0.00
            ]);
        }
    }
}
